# Generated by Django 5.0 on 2023-12-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
    ]
