# Generated by Django 5.0 on 2023-12-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Description',
            field=models.TextField(default='n'),
            preserve_default=False,
        ),
    ]
